version: "3.8"

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./PF:/var/www/html
    depends_on:
        - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planilha_financeira
    ports:
      - "3306:3306"